# src/config/config.yaml

# 向量存儲配置
vector_store:
  dimensions: 1024
  metric: cosine
  index_type: flat
  chunk_size: 1000
  chunk_overlap: 200

# 模型配置
models:
  # LlamaParse 配置
  llamaparse:
    parsing_instructions: |
      這是一份永續報告書，包含多個ESG指標。
      請特別注意：
      1. 數值型指標及其單位
      2. 表格中的數據
      3. 圖表展示的趨勢
      4. 各指標的所屬章節
      5. 年度比較數據
    
  # ImageBind 配置
  imagebind:
    use_half_precision: true
    batch_size: 32
    model_type: huge  # 可選: huge, large, base
    
  # 文本嵌入配置
  embedding:
    model_name: text-embedding-3-small
    max_tokens: 8000
    batch_size: 32

# 優化配置
optimization:
  cache_dir: ".cache"
  temp_dir: ".temp"
  max_retries: 3
  timeout: 30

# 輸出配置
output:
  excel_template: "templates/esg_report_template.xlsx"
  save_interim: true
  interim_dir: "interim"