# src/config/metrics_schema.yaml

# 環境面向 (E)
environmental:
  greenhouse_gas:
    name: "溫室氣體排放量"
    code: "E1.1"
    unit: "公噸CO2e"
    type: "numerical"
    possible_sources: ["table", "text", "chart"]
    validation:
      min: 0
      trend: "decreasing"
  
  water_usage:
    name: "用水量"
    code: "E2.1"
    unit: "立方米"
    type: "numerical"
    possible_sources: ["table", "text"]
    validation:
      min: 0

# 社會面向 (S)
social:
  employee_training:
    name: "員工全年平均學習時數"
    code: "S1.1"
    unit: "小時"
    type: "numerical"
    possible_sources: ["table", "text"]
    validation:
      min: 0
      recommended_min: 12
  
  compensation:
    name: "整體薪酬在業界水準"
    code: "S2.1"
    unit: "百分比"
    type: "percentage"
    possible_sources: ["table", "chart"]
    validation:
      min: 0
      max: 100
      recommended_min: 50

# 治理面向 (G)
governance:
  board_diversity:
    name: "董事會多元化程度"
    code: "G1.1"
    unit: "百分比"
    type: "percentage"
    possible_sources: ["table", "text"]
    validation:
      min: 0
      max: 100
      recommended_min: 30
  
  risk_management:
    name: "風險管理覆蓋率"
    code: "G2.1"
    unit: "百分比"
    type: "percentage"
    possible_sources: ["table", "text"]
    validation:
      min: 0
      max: 100
      recommended_min: 90